name: checks

on:
  pull_request: 
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
            go-version-file: 'go.mod'
      - name: unit tests
        run: |
          go test ./...
